### ISSUE TITLE
Blanking the Info Bar Tooltip setting crashes the game

### ISSUE THREAD

**Issue by SlyAceZeta** [cas-c/WhereAmIAgain#25] opened 2023-10-10 05:10 UTC
I had two separate crashes tonight, the first was after holding down the DEL key in the Info Bar Tooltip setting, the second was after selecting all contents of the setting and deleting it. Both crash reports have been sent to the Dalamud server, but I don't know if you have access to the private channels they made.

**Comment by MidoriKami** [comment] 2023-10-10 05:15
Ah thanks, I keep forgetting to write this issue on my todo list.

I do not have direct access to the reports, I can request access if needed, but I already know the cause of the issue. I just keep forgetting to do it because I've been very busy lately.

**Comment by MidoriKami** [comment] 2023-10-10 06:19
Fixed in 6572f4dbdb01f48681e2289b6bdac66bcfb3ad89

**Closed as completed by MidoriKami** 2023-10-10 06:19 UTC
